### ISSUE TITLE
Version 1.1.1 builds with errors

### ISSUE THREAD

**Issue by HansHagberg** [zcoinofficial/ccminer#10]
Ubuntu 16.04
CUDA 9.1

cuda_mtp/mtp.cu: In function ‘int scanhash_mtp(int, int, work*, uint32_t, long unsigned int*, mtp*)’:
cuda_mtp/mtp.cu:220:1: error: jump to label ‘TheEnd’ [-fpermissive]
 TheEnd:
 ^
cuda_mtp/mtp.cu:149:44: note:   from here
  if (work_restart[thr_id].restart) goto TheEnd;
                                            ^
cuda_mtp/mtp.cu:152:5: note:   crosses initialization of ‘int order’
   int order = 0;
     ^
Makefile:2505: recipe for target 'cuda_mtp/mtp.o' failed
make[2]: *** [cuda_mtp/mtp.o] Error 1
make[2]: Leaving directory '/DBC/MTP/ccminer-1.1.1-test'
Makefile:2043: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/DBC/MTP/ccminer-1.1.1-test'
Makefile:617: recipe for target 'all' failed
make: *** [all] Error 2

No problem building earlier version in the same environment.
Built what is displayed as v0.0.4-djm34 on December 7. 
Still running it with zero problems since launch of mainnet.

**Comment by djm34** [comment]
what did you downloaded exactly ? (this error specific to linux was corrected about a week ago)

**Comment by HansHagberg** [comment]
ccminer-1.1.1-test.tar.gz was the file

**Comment by HansHagberg** [comment]
Tested the latest 1.1.1 non-test version. That one built without errors.
