### ISSUE TITLE
Miner crashes - Keep alive watchdog needed

### ISSUE THREAD

**Issue by HansHagberg** [zcoinofficial/ccminer#16]
ccminer, Ubuntu 16.04, CUDA 9.1

Miner crashes frequently. Regardless of the reason, it would be very useful and profitable if the code would catch the crash and just restart.

**Comment by vapordwarf** [comment]
https://github.com/Undertrey/FarmWatchBot/releases

Works great with latest version of this ccminer.

**Comment by HansHagberg** [comment]
Linux versions basically useless at the moment. Latest one that can be built is 1.1.17 but it crashes within minutes. Older versions are stable but hashrate is useless.
Windows versions do not have same problems for some reason.

**Comment by HansHagberg** [comment]
Rant ?
The suggestion is to catch crashes within the code. That's a pretty standard design practice.
The miner is currently unstable and crashes for numerous reasons. There is no error handling so it's not possible to troubleshoot easily. 
My linux rigs are very high end with 128 GB RAM and all GPUs on 16x PCIe. They are for professional work but are mining in the background during idle periods.
Something is off with the Linux code because the windows miner works better.

It's also a fact that I can't build the latest published Linux code due to compile errors. This has been reported earlier but the issue was closed without a fix for the build error I put in the issue. I suspect there are different build issues and the fix covered only the original fault. I therefore opened a new issue on this for v 1.1.19.

A suggestion is that you ask questions instead of closing issues directly. A normal practice is to find a fix and then let the tester confirm it works before closing the error reports. After all, writing issues here is done in order to contribute to improving the product. If you prefer not to have error reports, I will stop.

**Comment by djm34** [comment]
The error you describe is the same as the one which got fixed, you need to pull the master. Also it is rather difficult to check what kind of problem you are experiencing, because so far no one reported it and you don't give any detail on how and when this crash happens
