### ISSUE TITLE
Error code = -22

### ISSUE THREAD

**Issue by vapordwarf** [zcoinofficial/ccminer#18]
I have the miner working on my desktop and 1 of my rigs. However, on the other 2, I get error code = -22 right after starting the miner. I thought it might be a system RAM issue,  but after adding an additional stick of RAM to give the rig 8GB like the working rig has, I still get the same error. Any assistance would be greatly appreciated.

**Comment by djm34** [comment]
it was found out that this error was due to a too small swap or pagefile. and basically you need to increase them to match ccminer demands. currently 4.5Gb/card (for swap not memory)
