### ISSUE TITLE
New MTP version locked to 16 intensity?

### ISSUE THREAD

**Issue by GehnDor** [zcoinofficial/ccminer#2]
https://github.com/zcoinofficial/ccminer/blob/3a20a069d6cc3f981595e4f06d06f99165d7e447/cuda_mtp/mtp.cu#L61

I seem unable to set intensity on the current release, will have to compile with modifications here - correct?

**Comment by lyolyalya** [comment]
yes.see the code remarks

NB: For the moment, the intensity is not adjustable, this project is still in developpement, this will be changed in the near future

**Comment by djm34** [comment]
solved in newer version
