### ISSUE TITLE
High reject rate.

### ISSUE THREAD

**Issue by mercuryminer** [zcoinofficial/ccminer#22]
[2018-12-30 11:45:13] submit_upstream_work stratum_send_line failed
[2018-12-30 11:45:13] ...retry after 30 seconds

Not much point waiting 30 secs to submit what will prob be stales shares after 30second wait. Leading to some of my miners with huge numbers of rejected shares.

**Comment by djm34** [comment]
this message error is due to  connection problem with the pool. This is a pool issue not a miner one
