### ISSUE TITLE
1.1.8 - Build error on Ubuntu (util.cpp)

### ISSUE THREAD

**Issue by jmarcott86** [zcoinofficial/ccminer#23]
I tried building 8b8e6898e1f91ab992ea62f9d8bd4fa5bf46869d for Linux, and got a "jump to label 'out' crosses initialization of 'char* JobID'" error in util.cpp. Problem is with this line:
https://github.com/zcoinofficial/ccminer/blob/8b8e6898e1f91ab992ea62f9d8bd4fa5bf46869d/util.cpp#L2494

Moving this up to line 2427 works.

**Comment by HansHagberg** [comment]
Tried building 1.1.9
This is the result:
g++ -DHAVE_CONFIG_H -I.  -fopenmp  -pthread -fno-strict-aliasing -std=c++11 -I./compat/bos-jansson -I/usr/local/cuda/include    -g -O2 -MT ccminer-util.o -MD -MP -MF .deps/ccminer-util.Tpo -c -o ccminer-util.o `test -f 'util.cpp' || echo './'`util.cpp
util.cpp: In function ‘bool stratum_notify_bos(stratum_ctx*, json_t*)’:
util.cpp:2537:1: error: jump to label ‘out’ [-fpermissive]
 out:
 ^
util.cpp:2477:9: note:   from here
    goto out;
         ^
util.cpp:2494:8: note:   crosses initialization of ‘char* JobID’
  char* JobID = (char*)malloc(2 * job_idsize + 1);
        ^
util.cpp:2537:1: error: jump to label ‘out’ [-fpermissive]
 out:
 ^
util.cpp:2466:8: note:   from here
   goto out;
        ^
util.cpp:2494:8: note:   crosses initialization of ‘char* JobID’
  char* JobID = (char*)malloc(2 * job_idsize + 1);
        ^
util.cpp:2537:1: error: jump to label ‘out’ [-fpermissive]
 out:
 ^
util.cpp:2450:8: note:   from here
   goto out;
        ^
util.cpp:2494:8: note:   crosses initialization of ‘char* JobID’
  char* JobID = (char*)malloc(2 * job_idsize + 1);
        ^
Makefile:1775: recipe for target 'ccminer-util.o' failed
make[2]: *** [ccminer-util.o] Error 1
make[2]: Leaving directory '/DBC/MTP/ccminer-1.1.9'
Makefile:2047: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/DBC/MTP/ccminer-1.1.9'
Makefile:621: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by djm34** [comment]
fixed. thanks for reporting
