### ISSUE TITLE
Can't build v 1.1.9 in Ubuntu 16.04

### ISSUE THREAD

**Issue by HansHagberg** [zcoinofficial/ccminer#24]
Code downloaded Dec 31  17:.00 UTC + 1
Output:

g++ -DHAVE_CONFIG_H -I.  -fopenmp  -pthread -fno-strict-aliasing -std=c++11 -I./compat/bos-jansson -I/usr/local/cud                                                                                             a/include    -g -O2 -MT ccminer-util.o -MD -MP -MF .deps/ccminer-util.Tpo -c -o ccminer-util.o `test -f 'util.cpp'                                                                                              || echo './'`util.cpp
util.cpp: In function ‘bool stratum_notify_bos(stratum_ctx*, json_t*)’:
util.cpp:2537:1: error: jump to label ‘out’ [-fpermissive]
 out:
 ^
util.cpp:2477:9: note:   from here
    goto out;
         ^
util.cpp:2494:8: note:   crosses initialization of ‘char* JobID’
  char* JobID = (char*)malloc(2 * job_idsize + 1);
        ^
util.cpp:2537:1: error: jump to label ‘out’ [-fpermissive]
 out:
 ^
util.cpp:2466:8: note:   from here
   goto out;
        ^
util.cpp:2494:8: note:   crosses initialization of ‘char* JobID’
  char* JobID = (char*)malloc(2 * job_idsize + 1);
        ^
util.cpp:2537:1: error: jump to label ‘out’ [-fpermissive]
 out:
 ^
util.cpp:2450:8: note:   from here
   goto out;
        ^
util.cpp:2494:8: note:   crosses initialization of ‘char* JobID’
  char* JobID = (char*)malloc(2 * job_idsize + 1);
        ^
Makefile:1775: recipe for target 'ccminer-util.o' failed
make[2]: *** [ccminer-util.o] Error 1
make[2]: Leaving directory '/DBC/MTP/ccminer-1.1.9'
Makefile:2047: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/DBC/MTP/ccminer-1.1.9'
Makefile:621: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by djm34** [comment]
the error has been fixed yesterday, you need to to pull the master. (that's the reason why this has been closed). I didn't communicate on it, but you could have checked before reopening the issue though...
