### ISSUE TITLE
Out of memory error on 6 x GTX 1070 with 1.1.12

### ISSUE THREAD

**Issue by dunlopr** [zcoinofficial/ccminer#25]
The latest vesion still working is 1.1.10.

**Comment by djm34** [comment]
can you post your log file ?

**Comment by dunlopr** [comment]
other information
Rig with 4gb RAM with an SSD.
Virtual memory: 52gb
No overclock and power limit 95.

**Comment by djm34** [comment]
try to reboot your system, decrease the intensity, increase (again a bit the virtual memory just to make sure, what you have is enough) 4Gb is may-be a little small though (but should be ok... provided nothing else is eating the memory). 
Can you try to run with 1 gpu, then increase the number up to the point it crashes again so it is possible to understand what is happening

**Comment by dunlopr** [comment]
The problem seems to come from lack of memory. 4GB of memory is not enough with your latest version. I am able to work with only 4 cards. I tried to increase virtual memory without success.

**Comment by djm34** [comment]
on the ram size, it needs only 300Mb/gpu

**Comment by DocRogan** [comment]
I have 12 x 1070.

had same problem as you. I put my virtual memory to 70gb and then it worked. Previous i had 60 for eth. 

So put virtual memory to 70gb and it will be ok.
I also have 4gb and celeron 1151

Hope it helps ! I wish cryptodagger dont have fee of 2percent + pool fee + el that is now really expensive ... its to many fees wanted to use this software but i could not make it run. i start ccminer.exe but nothing happens.

**Comment by nemosminer** [comment]
im testing this currently on 6x 1070ti rig getting same out of memory error as above.

i have vm set to 70gb 
4gb ram
celeron pro
win 10 

selecting 1 gpu it runs perfect 
keep doing this 2 then 3 then 4 works perfect up 2 5 cards ! but once the 6th is added i get out of mem error

i will add another 4gb ram so 8gb total and see if the 6th card will run

hope this helps

**Comment by nemosminer** [comment]
tried taking vm up to max i had 74gb total did NOT help..

can confirm that adding another 4gb ram to system now 8gb total it runs perfect on 6 x 1070tis 

so 8gb is need if you want to run 6 cards with windows 10

**Comment by nemosminer** [comment]
DW sorted

**Comment by dunlopr** [comment]
> Strange i have 70gb virtual and 4gb and it runs . But with crypto dredge

Haha Why write on the competitor's forum ??

**Comment by DocRogan** [comment]
> > Strange i have 70gb virtual and 4gb and it runs . But with crypto dredge
> 
> Haha Why write on the competitor's forum ??

Cuz i  want to use this program but i cant find how to edit but file and what to insert... anyone help me

**Comment by ayiphelmy** [comment]
does not validate on CPU! 6x1070ti i5 16GB ram 75 GB VM... mining on nicehash -i 16, so what i'm doing wrong?

Thanks

**Comment by djm34** [comment]
sometimes these types of error can be due to power issue...

**Comment by ayiphelmy** [comment]
1700 watt platimax psu use for 6x 1070ti i think thats more than enough

**Comment by djm34** [comment]
does it work with 5 gpu ? (or could be a riser issue)

**Comment by ayiphelmy** [comment]
i have 1 rig with 3 rx 480 gpu and other use 6 x rx480 all have same problem
