### ISSUE TITLE
util.cpp:1434:13: error: cannot convert ‘bool’ to ‘json_t*’ in return

### ISSUE THREAD

**Issue by eLvErDe** [zcoinofficial/ccminer#30]
Hello,

1.1.13 does not build anymore:

```
util.cpp: In function ‘json_t* stratum_recv_line_bos(stratum_ctx*)’:
util.cpp:1434:13: error: cannot convert ‘bool’ to ‘json_t*’ in return
      return false;
             ^~~~~
```

**Comment by superwhyun** [comment]
Just replace 'false' to 'NULL'. It was compiled well for me. However, I'm not sure whether this may lead to any other issues such as memory leaking.

**Comment by djm34** [comment]
need to check, NULL should be ok though

**Comment by eLvErDe** [comment]
I went for rolling back to previous behavior, some goto returning an empty JS objet which looks ok to me, at least it built and seem to be working just fine

**Comment by Justaphf** [comment]
Ran into the same issue.  I think `return NULL` is the equivalent of the previous functionality, older compilers just implicitly converted between `false` and `NULL`, which both map to 0.  Newer compilers are doing a lot more safety checking to catch potential programmer errors easily missed/hidden due to the implicit conversions that were previously accepted silently.

**Comment by djm34** [comment]
Can you tell me to what it is pointing actually, because I don't see any conversion from bool to json

**Comment by Justaphf** [comment]
In current master (commit 20d0432) inside of util.cpp function
`json_t *stratum_recv_line_bos(struct stratum_ctx *sctx)`
expects a `json_t*` return type but on L1432 you have the following check, which returns a boolean.
```
				if (!bos_validate(sctx->sockbuf, sctx->sockbuf_bossize)) {
					applog(LOG_ERR, "stratum_recv_line: not a serialized object");
					return false;

				}
```

**Comment by djm34** [comment]
indeed... ok I fixed it. (removed the whole condition which shouldn't happened in anyway. 
the changes has been pushed to master
