### ISSUE TITLE
Rtx / cuda10 support?

### ISSUE THREAD

**Issue by MaynardMiner** [zcoinofficial/ccminer#34]
Adding 

nvcc_ARCH += -gencode=arch=compute_75,code=\"sm_75,compute_75\"

Results in successful build, but when running I get nothing but "does not validate on cpu".

Before I continue, is it possible to compile with cuda 10, or is it failing because official release does not support rtx cards / cuda 10?

**Comment by djm34** [comment]
cuda 10 and RTX cards are supported
try to replace the 
nvcc_ARCH   = -gencode=arch=compute_61,code=\"sm_61,compute_61\"
with 
nvcc_ARCH   = -gencode=arch=compute_75,code=\"sm_75,compute_75\"

Although your issue might be related to not enough RAM and/or swap. You need 4.7Gb/per card of swap and 230Mb of RAM per card

**Comment by MaynardMiner** [comment]
I did, but I will increase SWAP, and see what I get. I know I have more than enough RAM.

But I wanted to make sure that you could use:

nvcc_ARCH = -gencode=arch=compute_75,code="sm_75,compute_75"

**Comment by MaynardMiner** [comment]
Is is not possible to use both? Usually you can in my experience.

I am trying to make a generic x64-86 build, that will work on GTX and RTX cards, if possible.

**Comment by djm34** [comment]
it is possible, I was trying to give a way to isolate the problem in case it comes from the compilation. However I don't think it is the case. 
Can you check the the "doesn't validate on cpu" happens for both card or only the RTX
