### ISSUE TITLE
 make error after git clone latest release with latest commit 01cbc4a  on Ubuntu 16.04

### ISSUE THREAD

**Issue by dxs95** [zcoinofficial/ccminer#35]
Hello!
Thanks for all !!!
Make error after git clone latest release with latest commit 01cbc4a  on Ubuntu 16.04

......
nvcc -gencode=arch=compute_61,code=\"sm_61,compute_61\" -I/usr/local/cuda/include -I. -I./compat/bos-jansson -std=c++11 --ptxas-options="-v" --maxrregcount=128 -o cuda_mtp/mtp.o -c cuda_mtp/mtp.cu
cuda_mtp/mtp.cu(256): warning: variable "lenMax" was declared but never referenced

cuda_mtp/mtp.cu(257): warning: variable "len" was declared but never referenced

cuda_mtp/mtp.cu(59): warning: variable "diff" was declared but never referenced

cuda_mtp/mtp.cu(60): warning: variable "TheNonce" was declared but never referenced

cuda_mtp/mtp.cu(443): warning: variable "lenMax" was declared but never referenced

cuda_mtp/mtp.cu(444): warning: variable "len" was declared but never referenced

cuda_mtp/mtp.cu(401): error: transfer of control bypasses initialization of:
            variable "TotHash"
(404): here

cuda_mtp/mtp.cu(314): warning: variable "diff" was declared but never referenced

cuda_mtp/mtp.cu(315): warning: variable "TheNonce" was declared but never referenced

cuda_mtp/mtp.cu(30): warning: variable "fillGpu" was declared but never referenced

1 error detected in the compilation of "/tmp/tmpxft_000033c4_00000000-6_mtp.cpp1.ii".

Best regards

**Comment by djm34** [comment]
Thanks for the report, I will look into it.

**Comment by dxs95** [comment]
Thanks for attention.
Please, take a look at this.
The program (windows &  linux  version), when specifying command line parameter the –x or –proxy, performs the connection directly. When an external connection is disconnected from the Internet - only the local network (the proxy server is located on the local network and has access to the Internet) the program does not connect to the pool.

**Comment by djm34** [comment]
when you have new issue, please create a different issue (this was completely unnoticed until now...).
Better post the problem on discord as well
