### ISSUE TITLE
Virus blocker

### ISSUE THREAD

**Issue by Starman07** [zcoinofficial/ccminer#37]
Every time I try to download eith CCMINER or Cryptodredge both Windows defender and AVG detect trojan or malware and terminate the download. What do I need to do

**Comment by jeja2000** [comment]
One way is to add an Exception for CCMINER. So AVG stops reporting about it.

**Comment by Starman07** [comment]
Thank you Jesper. Will do.
Jack

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by djm34** [comment]
can't do anything, it seems now that every miners application gets tagged as virus/miner

**Comment by Starman07** [comment]
Cheers. I have found a way to recover and add an exception in AVG.
.
Cheers
Jack

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
