### ISSUE TITLE
Tried Latest release v1.1.17 Solo mining seems broken. 

### ISSUE THREAD

**Issue by jeja2000** [zcoinofficial/ccminer#38]
Seems not to get past GPU #0 Solo Mode, Intensity set to 20, 1048576 cuda threads. 

Waited atleast 5 minute to get some output of nonce and hashrate.

**Comment by djm34** [comment]
I'll have a look

**Comment by djm34** [comment]
ok, found out the problem. I deactivated the hashrate printout for some test last week and this got committed at the same time as the last change. 
aside from that and block difficulty which isn't reported correctly for solo, everything is fine

**Comment by jeja2000** [comment]
Ahh, I see. 
Thanks for fast feedback.
