### ISSUE TITLE
Clearification wanted. Should you use longpoll when solomining?

### ISSUE THREAD

**Issue by jeja2000** [zcoinofficial/ccminer#39]
Website doesnt have --no-longpoll argument 
https://zcoin.io/guide-on-how-to-mine-zcoin-xzc/

But on the readme.md it is in the example. 

What are pros and cons?

**Comment by djm34** [comment]
longpoll should definitely be used when solo mining, it is what informs the miner when a new block is broadcast on the network.

Always follow example given in RUN-ZCOIN-MTP.cmd which is given in every release

The guide is outdated. There was a problem at that time getting longpoll working which has been solved.

**Comment by jeja2000** [comment]
Great. I just noted the readme here on github.
