### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by deh8551** [zcoinofficial/ccminer#4]
Compiled from git on Ubuntu 16 which complied, although there were warnings about unused entries.  When trying to run agains 2miners pool, the miner starts up, but then dies listing 28477 Segmentation fault (core dumped).  Running with the debug switch does not output any information related to the segmentation fault.

**Comment by deh8551** [comment]
Compiled the latest build, commit 7076548, and now receiving error 11733 Killed  instead of 28477 Segmentation fault (core dumped).

**Comment by djm34** [comment]
the "killed" is due to the fact you are using more memory than there is on the system...
I assume this problem is solved in the most recent version. 
I will close this issue (if not feel free to re-open it)
