### ISSUE TITLE
Execution fail on GTX960M

### ISSUE THREAD

**Issue by xaldyz** [zcoinofficial/ccminer#40]
Hello!

I am trying to get the code working on a machine with a GTX960M. Since I see the last tag has a "test" label, I stuck with the 1.1.17. I am targeting the MTP algorithm, for the moment.
The code compiling went fine, but I get the error "cudaErrorInvalidValue" on [this line](https://github.com/zcoinofficial/ccminer/blob/0c8f00af5ce50f3b87bc9024a117977532f6fa36/cuda_mtp/cuda_mtp.cu#L2039). I backtracked the problem and it seems (at least for my architecture, that has 2 GB of dedicated VRAM) the problem initially originated [here](https://github.com/zcoinofficial/ccminer/blob/0c8f00af5ce50f3b87bc9024a117977532f6fa36/cuda_mtp/cuda_mtp.cu#L1383), sinche the resulting pointer is 0x00000000.
I tried to reverse to version 1.1.12, but then issue #28 arise, giving the error "Result for 000000000 does not validate on CPU", even if I suspect the issue is not the same

However, setting [argon_memcost](https://github.com/zcoinofficial/ccminer/blob/0c8f00af5ce50f3b87bc9024a117977532f6fa36/cuda_mtp/cuda_mtp.cu#L26) e [memcost](https://github.com/zcoinofficial/ccminer/blob/0c8f00af5ce50f3b87bc9024a117977532f6fa36/cuda_mtp/mtp.cu#L9) to a value of 4*4*1024 (meaning 16 MB of RAM) instead of 4*1024*1024 (meaning 4 GB of RAM) allows the memory to be created, but fails [shortly after](https://github.com/zcoinofficial/ccminer/blob/99951cf98180ccb6d1bfb23d5231df4407794c3e/cuda_mtp/mtp.cu#L175) (obviously, that memory is not allocated!).

Before I invest too much energy in these issues, I'd like to ask you if 1-2GB of VRAM could (at least in theory) be sufficient, but the actual code configuration requires more than that. I'd like to contribute but I can't be so helpful if my hardware just does not support the algorithm 😄

**Comment by djm34** [comment]
Hello,

you hardware doesn't support mtp algorithm which requires here 4Gb of memory. 

If in theory one could create a mtp algo using only a  16Mb of ram (which would be rather insecure) it was chosen long ago by zcoin team to use a scratchpad of 4Gb, and this number can't be modified. 
If you were modifiying this number in the miner, the miner would still mine but no valid solution would be found.

**Comment by xaldyz** [comment]
Yeah, 16 MB was only a matter of fact to check if the problem was exclusively to attribute to a memory allocation problem.
I was wondering if there could be a way to reduce the memory amount requested to mine to use my card that only has 2 GB of RAM, I didn't think that the memory usage was actually part of the specification to make the things work!
Thank you for your explanation 😄 

PS: it's not related to this issue, but since I had quite some troubles to compile your work under Windows due to some solution related problem (libraries name incorrect, missing define), could it help if I manage to switch using a more robust build system (i.e.: CMake) than using Visual Studio solution and then perform a pull request?
I'm asking so I won't waste time If you are not interested!

**Comment by djm34** [comment]
you just need to clone the github release and compile with visuall studio 2015. 
everything is including even the libraries.
You need to compile for Release and x64

**Comment by xaldyz** [comment]
As I said, I was eventually able to compile everything, but the "open and compile" just doesn't work out of the box.
The problems I found are related to:
1. Missing HAVE_CONFIG_H define in the configuration (Debug)
2. In the linker section, there are libraries with names that are not included in the project (altough they are there, with a different name, like for example libcurl.x64.lib that is present with libcurl.lib, check it!) (Debug)
3. You need to manually select the CUDA version (I had 10.1 installed, but the 10.0 version was selected)
4. In my case I have a card with 3.5 compute capability, but in the specification the code was targeted to CC 5.2+ (in x64)
For the missing libraries, probably you have some other include and libraries in your path, that's why you don't notice any error.

If you know where to look, these are quite easily fixable, but still it took me quite a bit to recognize the errors (example: stdint.h was not included due HAVE_CONFIG_H define missing).
In my opinion, everything would be cleaner and more polish using the solution I proposed in previous post, and this would likely lower the bug due to incorrect configuration between linux and windows. But I understand if you are not interested in this kind of contribution, and this is why I asked beforehand to avoid investing my time into something that in the end would have not been used 😉

PS: i tried to download the version 1.1.17 in a ZIP file, open the Visual Studio solution in Visual Studio 2019 community (upgrading the solution), changed the "Build dependencies" from "CUDA 10.0" to "CUDA 10.1" (the one I have), have to change the "Code generation" (I selected inherit from parent) and everything compiled fine. So yeah, the problems I listed before is mostly located in the debug configuration!

**Comment by djm34** [comment]
The Debug version hasn't never been maintained (over the past 4 years).
As I said you need to compile for "Release" and "x64".
