### ISSUE TITLE
Start failed on GTX1060: Unable to query number of CUDA devices!

### ISSUE THREAD

**Issue by travek** [zcoinofficial/ccminer#41]
Hi!

I downloaded MTP miner, I have GTX 1060 on board. 
I have the following issue when started ccminer:
Unable to query number of CUDA devices! Is an nVidia driver installed?

I think I have all drivers installed. What I need to check ? What can me missed ?

**Comment by travek** [comment]
Fixed - I installed last version of CUDA

**Comment by djm34** [comment]
hmm you don't need to install cuda, but what cuda did, is to install new drivers. 
What you described is a driver problem
