### ISSUE TITLE
runaway memory usage on Win10

### ISSUE THREAD

**Issue by thoraxe** [zcoinofficial/ccminer#44]
Win10 Pro, 64-Bit
ccminer 1.1.23
launched via nicehash miner 1.9.1.5

After running for a while, ccminer.exe is using a tremendous amount of memory (11Gi+). I had noticed that after updating NHML to the most recent version that I was getting weird system crashes and instability. I couldn't figure it out. Then I dug into the system error log and saw some out-of-memory type errors. I fired up task manager and noticed that ccminer.exe was using nearly all of the system memory after running for a while.

Just now after only a minute or two memory usage was 450Mi+

I'm not totally sure what's going on here but happy to add more debug flags or help troubleshoot otherwise.

**Comment by djm34** [comment]
sorry for the late reply.
ccminer 1.1.23 does not support nicehash stratum. 
instabilities have been corrected in 1.1.24, however nicehash isn't supported.
