### ISSUE TITLE
Stability Issues - Randomly crashes

### ISSUE THREAD

**Issue by VoskCoin** [zcoinofficial/ccminer#46]
Windows 10 rig running 6x 1070 TI 16gb system ram 2600x ryzen, rig is stable on other coins, runs in a cool 70f environment. The miner will simply randomly crash whether it is 12 hours later, 2 days later, or a day later. It has happened ~10 times within the last 2 weeks, next time I will grab a screenshot w/ more information and update if the miner window remains open (normally does).

![Screen Shot 2019-07-16 at 1 34 05 PM](https://user-images.githubusercontent.com/34382863/61316358-cd3ded00-a7ce-11e9-81be-7901facb268b.png)

**Comment by djm34** [comment]
which release is this ? and what cause the crash ?
release 23 is supposed to crash on connection problem (this is under investigation). the command line should be within a loop to allow an automatic restart when this happens

example: 
loop: 
command line
goto loop

**Comment by VoskCoin** [comment]
@djm34 can you please post a full example bat? mine is not restarting when it crashes due to a connection problem and I am running the latest version 1.1.23

**Comment by djm34** [comment]
in your bat file you need this: 

loop:
ccminer -a mtp -o stratum+tcp://zcoin.mintpond.com:3000  -u aChWVb8CpgajadpLmiwDZvZaKizQgHxfh5.worker -p 0,strict,verbose

goto loop

**Comment by dhan000** [comment]
The machine restarts at five to ten minutes intervals.
it continues to randomaly crash.
6x1070ti
ubuntu 16.04
Nvidia Driver Version: 418.56 

gtx1060 running on the same version also no problem.

**Comment by djm34** [comment]
what pool are you using ? 
(can you try another pool and see if you have the same problem, pool with high ping are more likely to get these sort of problem... assuming it is a problem related to connection)

**Comment by dhan000** [comment]
I tried 2miners.com and nicehash.
No other connection problem, the other program is running quite stable.

**Comment by djm34** [comment]
nicehash isn't supported...

**Comment by djm34** [comment]
please have a look at the latest release 1.1.24 
(https://github.com/zcoinofficial/ccminer/releases/tag/1.1.24)
It should solve most of the crash problems encountered lately.

**Comment by VoskCoin** [comment]
goto loop fixed the issue when mining on 2miners but my miner is still crashing mining @ mintpond, I will try the latest version now and see if that remedies the issue.
