### ISSUE TITLE
Full list of nvidia gpu hash rate ?

### ISSUE THREAD

**Issue by rieniter** [zcoinofficial/ccminer#47]
Hello, i'm currently using 1070 for mining, and it is about 2.5MH/s same as announcement. The announcement also say about 1080 and 2080ti.

I would like to know hash rate about 1660, 1660ti, 2060, 2060S, 2070, 2070S. How do i get that result ? In whattomine, it said that 1070 only 2.1MH/s, and 1660 = 1.95 MH/s > 1660Ti = 1.85 MH/s ( I don't know this result is joking or what, non Ti weak than Ti )

**Comment by djm34** [comment]
the 1660 is doing 2065khash/s 
the 1070 is doing 2.5-2.6MHash/s
for the rest may-be you should join zcoin discord channel
