### ISSUE TITLE
Source code of latest version

### ISSUE THREAD

**Issue by mzk32** [zcoinofficial/ccminer#49]
Where is the source code of latest version 1.1.26? the master branch contains version 1.1.17 which is quite old.

I see the releases of version  1.1.18-test until 1.1.26 all of them are tagging the same commit 99951cf which is version 1.1.17

Will the source code of 1.1.26 open sourced?

**Comment by djm34** [comment]
the source code isn't available at the moment

**Comment by mzk32** [comment]
i use linux and the binary provided in the release page doesn't work on my machine, only by compiling from the source did the miner works, hence the need for the source code.

this is the error i got:
```
./ccminer-linux-cuda101: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```
on which path does the binary looks for libcrypto?

**Comment by djm34** [comment]
you probably need to install the package libcrypto
if it is already on your machine, you need to add the path to that dynamic library into LD_LIBRARY_PATH

**Comment by mzk32** [comment]
Ubuntu 19.04 uses libcrypto.so.1.1 however i managed to get libcrypto.so.1.0.0 from a snap package, and now i got this error:

```
/usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./ccminer-linux-cuda101)
```
i couldn't find a way to fix it since Ubuntu no longer provide libcurl3. could you provide the binary compiled with libcurl4?

**Comment by djm34** [comment]
do you have the package libcurl4-openssl-dev that's the one which should be installed ?

**Comment by mzk32** [comment]
yes, i have it installed.

```
$ dpkg -l | grep libcurl4-openssl-dev
ii  libcurl4-openssl-dev:amd64                                  7.64.0-2ubuntu1.1                                           amd64        development files and documentation for libcurl (OpenSSL flavour)
```
note that i could compile the source code of 1.1.17 and have the compiled binary run just fine
