### ISSUE TITLE
MTP, false positive when finding a solution to a block

### ISSUE THREAD

**Issue by Antonios-P** [zcoinofficial/ccminer#50]
I started mining Zcoin today with the latest ccminer. Everytime my GPU thinks it has found a solution to a block, it says this, ```False positive. Nonce=0198e90a Hash:43ad3f52c78e64e61f1c9e6a8bc8f7d1d9222d4e9dc5dd98e2963b76c23c50db /n
[2019-07-31 05:18:10] GPU #0: result for 0198e90a does not validate on CPU!```. Any help is appreciated!

**Comment by djm34** [comment]
How often this happens ? 

This is most likely due to minimum difficulty used to consider that a solution found by the gpu, could be below target. On GPU only the last 32bit are examined, while on cpu validation and POW assembling, it looks at the full target 256bit. So it is normal to have a false positive once in a while. 

There is nothing to worry if you see that once in a while

**Comment by Antonios-P** [comment]
I do see it once in a while, but only when it thinks it has found a solution to the block.

**Comment by djm34** [comment]
yeah it seems to be consistant with what I was saying. It is just the search on a smaller difficulty than the one expected (I could very increase the minimum difficulty actually and pass to 64bits to decrease the number of occurrences)

**Comment by djm34** [comment]
why the stratum difficulty is so low ? 0.0007 is really low for gpu (this in "mintpond difficulty" something like 46)

**Comment by Antonios-P** [comment]
Ok. It seems that I am still getting payouts from the pool, so it shouldn't be a big deal. Should the miner be having a difficulty less than one though?

**Comment by Antonios-P** [comment]
I'm gonna close this, because I still get payouts, and I only have it every 50 accepted shares. Take care!

**Comment by djm34** [comment]
a difficulty of 1 is a lot as far as mtp is concerned (after it depends a bit on your hashrate). 

I always goes back to mintpond equivalent, but a difficulty of 1 would be 65536 in mintpond unit while usually a difficulty of a 1080ti should be around 1000-2000 (ie 0.015-0.030)
