### ISSUE TITLE
cuda 9.2 not supported? didnt compile

### ISSUE THREAD

**Issue by tymoteuszrogalewski** [zcoinofficial/ccminer#51]
version 1.2.1 - do not compile with CUDA 9.2:
nvcc fatal   : Unsupported gpu architecture 'compute_75'

With CUDA 10.0 compiled successfully.

Compiled using this line:
export PATH=$PATH:/usr/local/cuda/bin && ./autogen.sh && ./configure && make -j12

Can You help me or definitely dropped cuda 9.2 support?

I dont remember is 1.2.0 I compiled manually or get official binary, but older versions always compiled ok under 9.2 and 10.0

**Comment by djm34** [comment]
to compile with cuda 9.2, you need to edit makefile.am and comment or remove the line regarding compute_75 near the end of the file. then redo autogen.sh; ./configure; make
(However, it is probably better to use cuda 10.1)

**Comment by tymoteuszrogalewski** [comment]
Thank you. It works ;-)
We need few different versions od cuda support as possible for compatibility with a lot of machines that are not upgraded to newer cuda.
