### ISSUE TITLE
how to build on Linux with multi gpu support

### ISSUE THREAD

**Issue by wekaz** [zcoinofficial/ccminer#6]
how to build on Linux with multi gpu support

**Comment by djm34** [comment]
use the test branch

git clone --branch test https://github.com/zcoinofficial/ccminer
cd ccminer
chmod u+x autogen.sh
./autogen.sh
./configure
./make clean; make

Prior doing this you will have to have developper package install on your system as well as cuda

sudo apt-get update && sudo apt-get -y dist-upgrade
sudo apt-get -y install gcc g++ build-essential automake linux-headers-$(uname -r) git gawk libcurl4-openssl-dev libjansson-dev xorg libc++-dev libgmp-dev python-dev


then you'll need to instal nvidia drivers and cuda. I would suggest install the drivers which are included in cuda 10.
